---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-machine-api
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - openshift-machine-api
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: baremetal-operator
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: baremetal-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
