---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: baremetal-operator-group
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - openshift-machine-api
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: baremetal-operator
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: baremetal-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provisioningNetwork: "Disabled"
  watchAllNamespaces: true
