apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  plugins:
    - advanced-cluster-security
    - acm-console.openshift.io
    - gitops-plugin
    - networking-console-plugin
    - monitoring-plugin
    - odf-client-console
    - odf-console
