apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Explicitly including everything ensures you don't miss anything
# and gives you control over the order if necessary.
resources:
  - local-storage-operator.yaml
  - LocalVolumeDiscovery.yaml
  - LocalVolume.yaml
  - StorageCluster.yaml
  - StorageClass.yaml
  - ClusterIssuer.yaml
  - certs.yaml
  - nginx-test.yaml

patches:
  - target:
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --dns01-recursive-nameservers-only
