apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disk-sdb
  namespace: openshift-local-storage
spec:
  # This selects which nodes the operator should look at
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: Exists 
  storageClassDevices:
    - storageClassName: "local-storage-sdb"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/sdb
