apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: odf-disks
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - dev-okd-master0
              - dev-okd-master1
              - dev-okd-master2
              - dev-okd-worker0
              - dev-okd-worker1
              - dev-okd-worker2
  storageClassDevices:
    - storageClassName: "odf-raw-disks"  # ODF will look for this name
      volumeMode: Block  # ODF requires Block mode, not Filesystem
      devicePaths:
        - /dev/sdb
