---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  central:
    exposure:
      route:
        enabled: true
    resources:
      requests:
        cpu: 200m
        memory: 4Gi
    db:
      resources:
        requests:
          cpu: 150m
          memory: 4Gi
  scanner:
    analyzer:
      resources:
        requests:
          cpu: 200m
          memory: 1500Mi
    db:
      resources:
        requests:
          cpu: 150m
          memory: 200Mi
  scannerV4:
    indexer:
      resources:
        requests:
          cpu: 200m
          memory: 1500Mi
    matcher:
      resources:
        requests:
          cpu: 100m
          memory: 1500Mi
    db:
      resources:
        requests:
          cpu: 150m
          memory: 200Mi
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs-central-link
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  location: ApplicationMenu
  text: Advanced Cluster Security
  href: https://central-stackrox.apps.okd.dev.tsew.net
  applicationMenu:
    section: Security
    imageURL: https://central-stackrox.apps.okd.dev.tsew.net/static/images/redhat.svg
