---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  central:
    exposure:
      route:
        enabled: true
    db:
      resources:
        requests:
          cpu: 200m
          memory: 4Gi
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: advanced-cluster-security
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  displayName: Red Hat Advanced Cluster Security for OpenShift
  backend:
    type: Service
    service:
      name: central
      namespace: stackrox
      port: 443
      basePath: /
