---
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: okd-prod
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  clusterName: okd-prod
  sensor:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
  admissionControl:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
  perNode:
    collector:
      resources:
        requests:
          cpu: 50m
          memory: 320Mi
    compliance:
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
