---
apiVersion: v1
kind: Node
metadata:
  name: dell1
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
---
apiVersion: v1
kind: Node
metadata:
  name: dell2
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
---
apiVersion: v1
kind: Node
metadata:
  name: dell3
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
